---
- name: Install nginx
  become: yes
  become_user: root
  hosts: web
  tasks:
  - name: Install nginx package
    apt:
      name: nginx
      state: latest
  - name: check nginx service status
    service:
      name: nginx
      state: started
